export const colors = {
    backgroundColor: '#29281E',
    webkitLink: '#91CC00',
    inputPlaceholder: 'gray',
    darkSeparator: '#3E3F3A',
    loginFormColor: '#3E3F3A',
    textColor: '#fff',
    caution: 'yellow',
    loginBtnTextColor: '#000',
    loginBtnBgColor: '#91CC00',
    errorMsgColor: 'red',
    loginFormFooterSeparator: '#464646',
    blackCircleDiv: '#000000BF',
    dashboardBgColor: '#3E3F3A',
    datepickerCalendarBgColor: '#000',
    deleteAlertTextColor: 'red',
    deleteAlertAccBtnBgColor: 'red',
    dateRangeBgColor: '#3E3F3A',
    goalinfoBgColor: '#3E3F3A',
    progressBarBgColor: '#29281E',
    progressBarActiveState: '#91CC00',
    toggleBtnBg: '#F9F9FA1A',
    toggleBtnHover: '#29281E',
    ratioboxBg: '#3E3F3A',
    winColor: '#91CC00',
    lossColor: '#FF6262',
    genderSelection: '#3E3F3A',
    playerItem: '#3E3F3A',
    subscriptionTypeBorder: '#91CC00',
    subscriptionTypeBg: '#3E3F3A',
    matchComparisonText: '#ACACAC',
    comparisonContainerBg: '#29281E',
    analysisFooterBg: '#3E3F3A',
    analysisFooterSeparator: '#8E8E8E40', 
    roleSelectBg: '#3E3F3A',
    roleToggleBg: '#51524D',
    roleToggleActive: '#4C582F',
    roleSelectBtnColor: '#91CC00',
    journalPageCalenderSeparator: '#8D8D8D',
    journalDatePickerBg: '#3E3F3A',
    journalDatePickerCalenderBg: '#000',
    journalMatchCardBg: '#3E3F3A',
    matchSetColor: '#DF8340',
    matchCardSeparator: '#524e4e',
    questionScoreBg: '#DF8340',
    questionSeparator: '#4B4B4B',
    coachBadgeBg: '#91CC00',
    coachBadgeText: '#000',
    commentInputBg: '#29281E',
    sendMsgBadge: '#3E3F3A',
    msgInputBorder: '#fff',
    arrowActive: '#fff',
    commentCardBg: '#585858',
    selectTickBorder: '#62645C',
    selectedSubscriptionBg: '#91CC00',
    subscriptionBorder: '#3E3F3A',
    subscriptionSelectBtn: '#91CC00',
    subscriptionSelectBtnText: '#000',
    selectedSubscriptionText: '#000',
    playArrowContainer: '#000'
}

export function addColors(){
    const root = document.documentElement;
    for (const [key, value] of Object.entries(colors)) {
    // Converts camelCase to kebab-case (e.g., textDark -> --text-dark)
    const cssVarName = `--${key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()}`;
    root?.style.setProperty(cssVarName, value);
  }
}